{
 "title": "Общая информация",
 "panels": [
  {
   "title": "Push-service (Общее кол-во)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "push_sent_total", "legendFormat": "Отправленные Push" }
   ]
  },
  {
   "title": "SMS-service (Общее кол-во)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sms_sent_total", "legendFormat": "Отправленные SMS" }
   ]
  },
  {
   "title": "Email-service (Общее кол-во)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "email_sent_total", "legendFormat": "Отправленные Email" }
   ]
  },
  {
   "title": "Общая статистика",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "http_requests_received_total", "legendFormat": "{{instance}} — {{job}}" }
   ]
  }
 ]
}